import createContextHook from '@nkzw/create-context-hook';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useState, useEffect } from 'react';

export type Language = 'de' | 'en' | 'tr' | 'es' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
  isLoading: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  de: {
    // Tab Navigation
    'dashboard.title': 'Dashboard',
    'calendar.title': 'Kalender',
    'create.title': 'Erstellen',
    'analytics.title': 'Analytics',
    'settings.title': 'Einstellungen',
    
    // Analytics Screen
    'analytics.subtitle': 'Verfolgen Sie Ihre Social Media Performance',
    'analytics.7days': '7 Tage',
    'analytics.30days': '30 Tage',
    'analytics.90days': '90 Tage',
    'analytics.overview': 'Übersicht',
    'analytics.totalReach': 'Gesamtreichweite',
    'analytics.engagementRate': 'Engagement-Rate',
    'analytics.newFollowers': 'Neue Follower',
    'analytics.profileVisits': 'Profilbesuche',
    'analytics.platformPerformance': 'Plattform Performance',
    'analytics.followers': 'Follower',
    'analytics.engagement': 'Engagement',
    'analytics.reach': 'Reichweite',
    'analytics.topPerformingPosts': 'Top-Posts',
    'analytics.aiInsights': 'KI-Einblicke',
    'analytics.exceptional': 'Außergewöhnlich',
    'analytics.good': 'Gut',
    'analytics.average': 'Durchschnitt',
    'analytics.daysAgo': 'vor {days} Tagen',
    'analytics.weekAgo': 'vor 1 Woche',
    'analytics.videoPerforming': 'Video-Content performt 40% besser',
    'analytics.videoDescription': 'Ihre Video-Posts erhalten deutlich mehr Engagement als statische Bilder.',
    'analytics.createMoreVideos': 'Mehr Video-Content erstellen',
    'analytics.bestPostingTime': 'Beste Posting-Zeit: 14-16 Uhr',
    'analytics.timingDescription': 'Ihre Zielgruppe ist werktags nachmittags am aktivsten.',
    'analytics.scheduleMore': 'Mehr Posts für 14-16 Uhr planen',
    'analytics.hashtagTrending': '#productivity Hashtag im Trend',
    'analytics.hashtagDescription': 'Posts mit #productivity erhalten diese Woche 25% mehr Reichweite.',
    'analytics.useTrendingHashtags': 'Trending Hashtags verwenden',
    
    // Language Selection
    'language.select': 'Sprache auswählen',
    'language.german': 'Deutsch',
    'language.english': 'English',
    'language.turkish': 'Türkçe',
    'language.spanish': 'Español',
    'language.french': 'Français',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolgreich',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.done': 'Fertig',
    'common.logout': 'Abmelden',
    'common.saveSettings': 'Einstellungen speichern',
    'common.settingsSaved': 'Einstellungen gespeichert',
    'common.dangerZone': 'Gefahrenbereich',
    
    // Settings Screen
    'settings.profile': 'Profil',
    'settings.account': 'Konto',
    'settings.subscription': 'Abonnement',
    'settings.notifications': 'Benachrichtigungen',
    'settings.security': 'Sicherheit',
    'settings.language': 'Sprache & Region',
    'settings.appearance': 'Erscheinungsbild',
    'settings.privacy': 'Datenschutz',
    'settings.integrations': 'Integrationen',
    'settings.team': 'Team',
    'settings.backup': 'Backup',
    'settings.feedback': 'Feedback',
    'settings.support': 'Support',
    'settings.about': 'Über die App',
    
    // Profile Settings
    'profile.personalInfo': 'Persönliche Informationen',
    'profile.name': 'Name',
    'profile.email': 'E-Mail-Adresse',
    'profile.phone': 'Telefonnummer',
    'profile.billingAddress': 'Rechnungsadresse',
    'profile.businessInfo': 'Geschäftsinformationen',
    'profile.company': 'Unternehmen',
    'profile.industry': 'Branche',
    'profile.website': 'Website',
    'profile.profilePicture': 'Profilbild',
    'profile.changePhoto': 'Foto ändern',
    'profile.visibility': 'Sichtbarkeit',
    
    // Account Settings
    'account.changePassword': 'Passwort ändern',
    'account.currentPassword': 'Aktuelles Passwort',
    'account.newPassword': 'Neues Passwort',
    'account.confirmPassword': 'Passwort bestätigen',
    'account.deleteAccount': 'Konto löschen',
    'account.deleteWarning': 'Diese Aktion kann nicht rückgängig gemacht werden',
    
    // Subscription Settings
    'subscription.currentPlan': 'Aktueller Plan',
    'subscription.monthly': 'Monatlich',
    'subscription.yearly': 'Jährlich',
    'subscription.trial': 'Testphase',
    'subscription.active': 'Aktiv',
    'subscription.expired': 'Abgelaufen',
    'subscription.renewsOn': 'Verlängert sich am',
    'subscription.changePlan': 'Plan ändern',
    'subscription.cancelSubscription': 'Abonnement kündigen',
    'subscription.paymentMethod': 'Zahlungsmethode',
    'subscription.billingHistory': 'Rechnungsverlauf',
    
    // Notifications
    'notifications.pushNotifications': 'Push-Benachrichtigungen',
    'notifications.emailNotifications': 'E-Mail-Benachrichtigungen',
    'notifications.postReminders': 'Post-Erinnerungen',
    'notifications.analyticsAlerts': 'Analytics-Benachrichtigungen',
    'notifications.teamUpdates': 'Team-Updates',
    'notifications.marketingEmails': 'Marketing-E-Mails',
    
    // Security
    'security.twoFactor': 'Zwei-Faktor-Authentifizierung',
    'security.enable2FA': '2FA aktivieren',
    'security.disable2FA': '2FA deaktivieren',
    'security.deviceManagement': 'Geräteverwaltung',
    'security.activeDevices': 'Aktive Geräte',
    'security.loginHistory': 'Anmeldungsverlauf',
    
    // Privacy
    'privacy.dataExport': 'Daten exportieren',
    'privacy.dataDownload': 'Meine Daten herunterladen',
    'privacy.privacyPolicy': 'Datenschutzerklärung',
    'privacy.termsOfService': 'Nutzungsbedingungen',
    'privacy.cookieSettings': 'Cookie-Einstellungen',
    
    // Integrations
    'integrations.socialMedia': 'Social Media Kanäle',
    'integrations.connected': 'Verbunden',
    'integrations.notConnected': 'Nicht verbunden',
    'integrations.connect': 'Verbinden',
    'integrations.disconnect': 'Trennen',
    'integrations.thirdParty': 'Drittanbieter-Tools',
    
    // Team
    'team.members': 'Teammitglieder',
    'team.inviteMembers': 'Mitglieder einladen',
    'team.roles': 'Rollen & Berechtigungen',
    'team.admin': 'Administrator',
    'team.editor': 'Bearbeiter',
    'team.viewer': 'Betrachter',
    
    // Support
    'support.contactUs': 'Kontaktieren Sie uns',
    'support.phone': 'Telefon',
    'support.email': 'E-Mail',
    'support.helpCenter': 'Hilfe-Center',
    'support.reportBug': 'Fehler melden',
    'support.featureRequest': 'Feature-Anfrage',
    'support.feedback': 'Feedback senden',
    
    // About
    'about.version': 'Version',
    'about.buildNumber': 'Build-Nummer',
    'about.releaseNotes': 'Versionshinweise',
    'about.licenses': 'Lizenzen',
    'about.impressum': 'Impressum',
    
    // Appearance
    'appearance.theme': 'Design',
    'appearance.light': 'Hell',
    'appearance.dark': 'Dunkel',
    'appearance.system': 'System',
    'appearance.fontSize': 'Schriftgröße',
    'appearance.colorScheme': 'Farbschema',
    
    // Dashboard Screen
    'dashboard.goodMorning': 'Guten Morgen! 👋',
    'dashboard.readyToCreate': 'Bereit, großartigen Content zu erstellen?',
    'dashboard.aiContentSuggestion': 'KI-Content-Vorschlag',
    'dashboard.productivityTrending': '"Produktivitätstipps" sind im Trend! Erstelle jetzt ein Reel für 40% mehr Reichweite.',
    'dashboard.createNow': 'Jetzt erstellen',
    'dashboard.overview': 'Übersicht',
    'dashboard.totalFollowers': 'Gesamte Follower',
    'dashboard.engagementRate': 'Engagement-Rate',
    'dashboard.postsThisWeek': 'Posts diese Woche',
    'dashboard.reach': 'Reichweite',
    'dashboard.platforms': 'Plattformen',
    'dashboard.recentPosts': 'Aktuelle Posts',
    'dashboard.morningMotivation': 'Morgendliche Motivation',
    'dashboard.productivityTip': 'Schneller Produktivitätstipp',
    'dashboard.industryInsights': 'Brancheneinblicke Artikel',
    'dashboard.engagements': 'Interaktionen',
    'dashboard.viewDetails': 'Details anzeigen',
    'dashboard.hoursAgo': 'vor {hours}h',
    'dashboard.daysAgo': 'vor {days}d',
    
    // Calendar Screen
    'calendar.subtitle': 'Planen und terminieren Sie Ihre Posts',
    'calendar.scheduledPosts': 'Geplante Posts',
    'calendar.scheduled': 'Geplant',
    'calendar.draft': 'Entwurf',
    'calendar.january': 'Januar',
    'calendar.february': 'Februar',
    'calendar.march': 'März',
    'calendar.april': 'April',
    'calendar.may': 'Mai',
    'calendar.june': 'Juni',
    'calendar.july': 'Juli',
    'calendar.august': 'August',
    'calendar.september': 'September',
    'calendar.october': 'Oktober',
    'calendar.november': 'November',
    'calendar.december': 'Dezember',
    'calendar.monday': 'Mo',
    'calendar.tuesday': 'Di',
    'calendar.wednesday': 'Mi',
    'calendar.thursday': 'Do',
    'calendar.friday': 'Fr',
    'calendar.saturday': 'Sa',
    'calendar.sunday': 'So',
    'calendar.morningMotivation': 'Motivations-Quote am Morgen',
    'calendar.industryInsights': 'Brancheneinblicke und Trends',
    'calendar.quickTutorial': 'Schnelles Tutorial-Video',
    'calendar.communityUpdate': 'Community Update',
    'calendar.behindScenes': 'Behind the Scenes',
    
    // Create Screen
    'create.subtitle': 'Erstelle deinen nächsten viralen Post',
    'create.socialMediaAccounts': 'Social Media Konten',
    'create.connected': 'Verbunden',
    'create.notConnected': 'Nicht verbunden',
    'create.connect': 'Verbinden',
    'create.mediaUpload': 'Medien Hochladen',
    'create.fromGallery': 'Aus Galerie',
    'create.files': 'Dateien',
    'create.uploading': 'Wird hochgeladen...',
    'create.aiContentGenerator': 'KI Content Generator',
    'create.aiDescription': 'Lass die KI ansprechende Inhalte basierend auf Trends und deiner Marke erstellen',
    'create.generateContent': 'Content Generieren',
    'create.generating': 'Wird generiert...',
    'create.contentType': 'Content Typ',
    'create.post': 'Post',
    'create.reel': 'Reel',
    'create.story': 'Story',
    'create.selectPlatforms': 'Plattformen Auswählen',
    'create.description': 'Beschreibung',
    'create.descriptionPlaceholder': 'Schreibe deine Beschreibung hier...',
    'create.addHashtags': 'Hashtags Hinzufügen',
    'create.aiImprove': 'KI Verbessern',
    'create.aiContentIdeas': 'KI Content Ideen',
    'create.trendingHashtags': 'Trending Hashtags',
    'create.publishingOptions': 'Veröffentlichungsoptionen',
    'create.postNow': 'Jetzt Posten',
    'create.schedule': 'Planen',
    'create.permissionRequired': 'Berechtigung erforderlich',
    'create.galleryPermission': 'Wir benötigen Zugriff auf deine Galerie, um Bilder hochzuladen.',
    'create.uploadError': 'Fehler beim Hochladen der Dateien.',
    'create.connectAccountFirst': 'Bitte verbinde zuerst dein {platform} Konto, um Posts zu erstellen.',
    'create.accountConnected': '{platform} wurde erfolgreich verbunden!',
    'create.connectionFailed': 'Verbindung fehlgeschlagen. Bitte versuche es erneut.',
    
    // Settings Screen - Additional translations
    'settings.manageBilling': 'verwalten',
    'settings.manageDevices': 'verwalten',
    'settings.manageMembers': 'verwalten',
    'settings.comingSoon': 'Diese Funktion wird bald verfügbar sein.',
    'settings.confirmLogout': 'Möchten Sie sich wirklich abmelden?',
    'settings.confirmDelete': 'Konto wird gelöscht...',
    'settings.aiNotifications': 'KI-Benachrichtigungen bei außergewöhnlicher Performance',
    'settings.enabled': 'Aktiviert',
    'settings.disabled': 'Deaktiviert',
    'settings.contactMethod': 'Wie möchten Sie uns kontaktieren?',
    'settings.disconnect': 'trennen',
    'settings.confirmDisconnect': 'Möchten Sie {platform} wirklich trennen?',
    'settings.connectPlatform': '{platform} Konto verbinden?',
    'settings.errorSaving': 'Fehler beim Speichern der Einstellungen',
    'settings.madeWith': 'Made with ❤️ by SMY Agency',
    
    // Weekly Review
    'weekly.title': 'Dein Wochenrückblick ist da!',
    'weekly.subtitle': 'Hier ist deine Performance der letzten 7 Tage',
    'weekly.weekOf': 'Woche vom {start} - {end}',
    'weekly.performanceHighlights': 'Performance-Highlights',
    'weekly.totalReach': 'Gesamtreichweite',
    'weekly.totalEngagement': 'Gesamte Interaktionen',
    'weekly.newFollowers': 'Neue Follower',
    'weekly.profileVisits': 'Profilbesuche',
    'weekly.postsPublished': 'Veröffentlichte Posts',
    'weekly.comparedToLastWeek': 'im Vergleich zur Vorwoche',
    'weekly.percentMore': '+{percent}% mehr als letzte Woche',
    'weekly.percentLess': '{percent}% weniger als letzte Woche',
    'weekly.sameAsLastWeek': 'Gleich wie letzte Woche',
    'weekly.topPerformingPosts': 'Meistgesehene Inhalte',
    'weekly.platformPerformance': 'Plattform Performance',
    'weekly.insights': 'Einblicke & Erkenntnisse',
    'weekly.recommendations': 'Empfehlungen für nächste Woche',
    'weekly.viewFullAnalytics': 'Vollständige Analytics anzeigen',
    'weekly.createContent': 'Content erstellen',
    'weekly.schedulePost': 'Post planen',
    'weekly.likes': 'Likes',
    'weekly.comments': 'Kommentare',
    'weekly.shares': 'Shares',
    'weekly.views': 'Aufrufe',
    'weekly.engagementRate': 'Engagement-Rate',
    'weekly.averageEngagement': 'Durchschnittliche Interaktion',
    'weekly.bestPerformingDay': 'Bester Tag',
    'weekly.bestPerformingTime': 'Beste Zeit',
    'weekly.trendingHashtags': 'Trending Hashtags',
    'weekly.contentTypePerformance': 'Content-Typ Performance',
    'weekly.audienceGrowth': 'Zielgruppen-Wachstum',
    'weekly.engagementTrend': 'Engagement-Trend',
    'weekly.reachTrend': 'Reichweiten-Trend',
    'weekly.followerGrowth': 'Follower-Wachstum',
    'weekly.postFrequency': 'Post-Häufigkeit',
    'weekly.recommendation.createMoreVideos': 'Erstelle 2-3 Video-Reels für bessere Reichweite',
    'weekly.recommendation.postAtOptimalTime': 'Poste zwischen 14-16 Uhr für maximale Sichtbarkeit',
    'weekly.recommendation.useTrendingHashtags': 'Nutze #{hashtag} für 25% mehr Reichweite',
    'weekly.recommendation.increasePostFrequency': 'Erhöhe deine Post-Frequenz auf 5-7 Posts pro Woche',
    'weekly.recommendation.engageWithAudience': 'Antworte auf Kommentare innerhalb von 2 Stunden',
    'weekly.insight.videoPerformance': 'Video-Content performt 40% besser',
    'weekly.insight.bestPostingTime': 'Beste Posting-Zeit: 14-16 Uhr',
    'weekly.insight.hashtagTrend': '#{hashtag} ist im Trend',
    'weekly.insight.audienceActivity': 'Deine Zielgruppe ist werktags am aktivsten',
    'weekly.insight.contentTypeWinner': '{type} Content hat die beste Performance',
    'weekly.noDataYet': 'Noch keine Daten verfügbar',
    'weekly.noDataDescription': 'Verbinde deine Social Media Konten, um deinen ersten Wochenrückblick zu erhalten.',
    'weekly.connectAccounts': 'Konten verbinden',
    'weekly.generatingReport': 'Wochenrückblick wird erstellt...',
    'weekly.reportReady': 'Dein Wochenrückblick ist bereit!',
    'weekly.shareReport': 'Bericht teilen',
    'weekly.downloadReport': 'Als PDF herunterladen',
    'weekly.reach': 'Reichweite',
    'weekly.engagement': 'Interaktionen',
  },
  en: {
    // Tab Navigation
    'dashboard.title': 'Dashboard',
    'calendar.title': 'Calendar',
    'create.title': 'Create',
    'analytics.title': 'Analytics',
    'settings.title': 'Settings',
    
    // Analytics Screen
    'analytics.subtitle': 'Track your social media performance',
    'analytics.7days': '7 Days',
    'analytics.30days': '30 Days',
    'analytics.90days': '90 Days',
    'analytics.overview': 'Overview',
    'analytics.totalReach': 'Total Reach',
    'analytics.engagementRate': 'Engagement Rate',
    'analytics.newFollowers': 'New Followers',
    'analytics.profileVisits': 'Profile Visits',
    'analytics.platformPerformance': 'Platform Performance',
    'analytics.followers': 'Followers',
    'analytics.engagement': 'Engagement',
    'analytics.reach': 'Reach',
    'analytics.topPerformingPosts': 'Top Performing Posts',
    'analytics.aiInsights': 'AI Insights',
    'analytics.exceptional': 'Exceptional',
    'analytics.good': 'Good',
    'analytics.average': 'Average',
    'analytics.daysAgo': '{days} days ago',
    'analytics.weekAgo': '1 week ago',
    'analytics.videoPerforming': 'Video Content Performing 40% Better',
    'analytics.videoDescription': 'Your video posts are getting significantly more engagement than static images.',
    'analytics.createMoreVideos': 'Create more video content',
    'analytics.bestPostingTime': 'Best Posting Time: 2-4 PM',
    'analytics.timingDescription': 'Your audience is most active during afternoon hours on weekdays.',
    'analytics.scheduleMore': 'Schedule more posts for 2-4 PM',
    'analytics.hashtagTrending': '#productivity Hashtag Trending',
    'analytics.hashtagDescription': 'Posts with #productivity are getting 25% more reach this week.',
    'analytics.useTrendingHashtags': 'Use trending hashtags',
    
    // Language Selection
    'language.select': 'Select Language',
    'language.german': 'Deutsch',
    'language.english': 'English',
    'language.turkish': 'Türkçe',
    'language.spanish': 'Español',
    'language.french': 'Français',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.done': 'Done',
    'common.logout': 'Logout',
    'common.saveSettings': 'Save Settings',
    'common.settingsSaved': 'Settings Saved',
    'common.dangerZone': 'Danger Zone',
    
    // Settings Screen
    'settings.profile': 'Profile',
    'settings.account': 'Account',
    'settings.subscription': 'Subscription',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.language': 'Language & Region',
    'settings.appearance': 'Appearance',
    'settings.privacy': 'Privacy',
    'settings.integrations': 'Integrations',
    'settings.team': 'Team',
    'settings.backup': 'Backup',
    'settings.feedback': 'Feedback',
    'settings.support': 'Support',
    'settings.about': 'About',
    
    // Profile Settings
    'profile.personalInfo': 'Personal Information',
    'profile.name': 'Name',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.billingAddress': 'Billing Address',
    'profile.businessInfo': 'Business Information',
    'profile.company': 'Company',
    'profile.industry': 'Industry',
    'profile.website': 'Website',
    'profile.profilePicture': 'Profile Picture',
    'profile.changePhoto': 'Change Photo',
    'profile.visibility': 'Visibility',
    
    // Account Settings
    'account.changePassword': 'Change Password',
    'account.currentPassword': 'Current Password',
    'account.newPassword': 'New Password',
    'account.confirmPassword': 'Confirm Password',
    'account.deleteAccount': 'Delete Account',
    'account.deleteWarning': 'This action cannot be undone',
    
    // Subscription Settings
    'subscription.currentPlan': 'Current Plan',
    'subscription.monthly': 'Monthly',
    'subscription.yearly': 'Yearly',
    'subscription.trial': 'Trial',
    'subscription.active': 'Active',
    'subscription.expired': 'Expired',
    'subscription.renewsOn': 'Renews on',
    'subscription.changePlan': 'Change Plan',
    'subscription.cancelSubscription': 'Cancel Subscription',
    'subscription.paymentMethod': 'Payment Method',
    'subscription.billingHistory': 'Billing History',
    
    // Notifications
    'notifications.pushNotifications': 'Push Notifications',
    'notifications.emailNotifications': 'Email Notifications',
    'notifications.postReminders': 'Post Reminders',
    'notifications.analyticsAlerts': 'Analytics Alerts',
    'notifications.teamUpdates': 'Team Updates',
    'notifications.marketingEmails': 'Marketing Emails',
    
    // Security
    'security.twoFactor': 'Two-Factor Authentication',
    'security.enable2FA': 'Enable 2FA',
    'security.disable2FA': 'Disable 2FA',
    'security.deviceManagement': 'Device Management',
    'security.activeDevices': 'Active Devices',
    'security.loginHistory': 'Login History',
    
    // Privacy
    'privacy.dataExport': 'Data Export',
    'privacy.dataDownload': 'Download My Data',
    'privacy.privacyPolicy': 'Privacy Policy',
    'privacy.termsOfService': 'Terms of Service',
    'privacy.cookieSettings': 'Cookie Settings',
    
    // Integrations
    'integrations.socialMedia': 'Social Media Channels',
    'integrations.connected': 'Connected',
    'integrations.notConnected': 'Not Connected',
    'integrations.connect': 'Connect',
    'integrations.disconnect': 'Disconnect',
    'integrations.thirdParty': 'Third-Party Tools',
    
    // Team
    'team.members': 'Team Members',
    'team.inviteMembers': 'Invite Members',
    'team.roles': 'Roles & Permissions',
    'team.admin': 'Administrator',
    'team.editor': 'Editor',
    'team.viewer': 'Viewer',
    
    // Support
    'support.contactUs': 'Contact Us',
    'support.phone': 'Phone',
    'support.email': 'Email',
    'support.helpCenter': 'Help Center',
    'support.reportBug': 'Report Bug',
    'support.featureRequest': 'Feature Request',
    'support.feedback': 'Send Feedback',
    
    // About
    'about.version': 'Version',
    'about.buildNumber': 'Build Number',
    'about.releaseNotes': 'Release Notes',
    'about.licenses': 'Licenses',
    'about.impressum': 'Impressum',
    
    // Appearance
    'appearance.theme': 'Theme',
    'appearance.light': 'Light',
    'appearance.dark': 'Dark',
    'appearance.system': 'System',
    'appearance.fontSize': 'Font Size',
    'appearance.colorScheme': 'Color Scheme',
    
    // Dashboard Screen
    'dashboard.goodMorning': 'Good morning! 👋',
    'dashboard.readyToCreate': 'Ready to create amazing content?',
    'dashboard.aiContentSuggestion': 'AI Content Suggestion',
    'dashboard.productivityTrending': '"Productivity tips" are trending! Create a Reel now for 40% more reach.',
    'dashboard.createNow': 'Create Now',
    'dashboard.overview': 'Overview',
    'dashboard.totalFollowers': 'Total Followers',
    'dashboard.engagementRate': 'Engagement Rate',
    'dashboard.postsThisWeek': 'Posts This Week',
    'dashboard.reach': 'Reach',
    'dashboard.platforms': 'Platforms',
    'dashboard.recentPosts': 'Recent Posts',
    'dashboard.morningMotivation': 'Morning motivation post',
    'dashboard.productivityTip': 'Quick productivity tip',
    'dashboard.industryInsights': 'Industry insights article',
    'dashboard.engagements': 'engagements',
    'dashboard.viewDetails': 'View Details',
    'dashboard.hoursAgo': '{hours}h ago',
    'dashboard.daysAgo': '{days}d ago',
    
    // Calendar Screen
    'calendar.subtitle': 'Plan and schedule your posts',
    'calendar.scheduledPosts': 'Scheduled Posts',
    'calendar.scheduled': 'Scheduled',
    'calendar.draft': 'Draft',
    'calendar.january': 'January',
    'calendar.february': 'February',
    'calendar.march': 'March',
    'calendar.april': 'April',
    'calendar.may': 'May',
    'calendar.june': 'June',
    'calendar.july': 'July',
    'calendar.august': 'August',
    'calendar.september': 'September',
    'calendar.october': 'October',
    'calendar.november': 'November',
    'calendar.december': 'December',
    'calendar.monday': 'Mon',
    'calendar.tuesday': 'Tue',
    'calendar.wednesday': 'Wed',
    'calendar.thursday': 'Thu',
    'calendar.friday': 'Fri',
    'calendar.saturday': 'Sat',
    'calendar.sunday': 'Sun',
    'calendar.morningMotivation': 'Morning motivation quote',
    'calendar.industryInsights': 'Industry insights and trends',
    'calendar.quickTutorial': 'Quick tutorial video',
    'calendar.communityUpdate': 'Community Update',
    'calendar.behindScenes': 'Behind the Scenes',
    
    // Create Screen
    'create.subtitle': 'Create your next viral post',
    'create.socialMediaAccounts': 'Social Media Accounts',
    'create.connected': 'Connected',
    'create.notConnected': 'Not Connected',
    'create.connect': 'Connect',
    'create.mediaUpload': 'Media Upload',
    'create.fromGallery': 'From Gallery',
    'create.files': 'Files',
    'create.uploading': 'Uploading...',
    'create.aiContentGenerator': 'AI Content Generator',
    'create.aiDescription': 'Let AI create engaging content based on trends and your brand',
    'create.generateContent': 'Generate Content',
    'create.generating': 'Generating...',
    'create.contentType': 'Content Type',
    'create.post': 'Post',
    'create.reel': 'Reel',
    'create.story': 'Story',
    'create.selectPlatforms': 'Select Platforms',
    'create.description': 'Description',
    'create.descriptionPlaceholder': 'Write your description here...',
    'create.addHashtags': 'Add Hashtags',
    'create.aiImprove': 'AI Improve',
    'create.aiContentIdeas': 'AI Content Ideas',
    'create.trendingHashtags': 'Trending Hashtags',
    'create.publishingOptions': 'Publishing Options',
    'create.postNow': 'Post Now',
    'create.schedule': 'Schedule',
    'create.permissionRequired': 'Permission Required',
    'create.galleryPermission': 'We need access to your gallery to upload images.',
    'create.uploadError': 'Error uploading files.',
    'create.connectAccountFirst': 'Please connect your {platform} account first to create posts.',
    'create.accountConnected': '{platform} connected successfully!',
    'create.connectionFailed': 'Connection failed. Please try again.',
    
    // Settings Screen - Additional translations
    'settings.manageBilling': 'manage',
    'settings.manageDevices': 'manage',
    'settings.manageMembers': 'manage',
    'settings.comingSoon': 'This feature will be available soon.',
    'settings.confirmLogout': 'Do you really want to log out?',
    'settings.confirmDelete': 'Account will be deleted...',
    'settings.aiNotifications': 'AI notifications for exceptional performance',
    'settings.enabled': 'Enabled',
    'settings.disabled': 'Disabled',
    'settings.contactMethod': 'How would you like to contact us?',
    'settings.disconnect': 'disconnect',
    'settings.confirmDisconnect': 'Do you really want to disconnect {platform}?',
    'settings.connectPlatform': 'Connect {platform} account?',
    'settings.errorSaving': 'Error saving settings',
    'settings.madeWith': 'Made with ❤️ by SMY Agency',
    
    // Weekly Review
    'weekly.title': 'Your Weekly Review is Here!',
    'weekly.subtitle': 'Here\'s your performance from the last 7 days',
    'weekly.weekOf': 'Week of {start} - {end}',
    'weekly.performanceHighlights': 'Performance Highlights',
    'weekly.totalReach': 'Total Reach',
    'weekly.totalEngagement': 'Total Engagement',
    'weekly.newFollowers': 'New Followers',
    'weekly.profileVisits': 'Profile Visits',
    'weekly.postsPublished': 'Posts Published',
    'weekly.comparedToLastWeek': 'compared to last week',
    'weekly.percentMore': '+{percent}% more than last week',
    'weekly.percentLess': '{percent}% less than last week',
    'weekly.sameAsLastWeek': 'Same as last week',
    'weekly.topPerformingPosts': 'Top Performing Content',
    'weekly.platformPerformance': 'Platform Performance',
    'weekly.insights': 'Insights & Analytics',
    'weekly.recommendations': 'Recommendations for Next Week',
    'weekly.viewFullAnalytics': 'View Full Analytics',
    'weekly.createContent': 'Create Content',
    'weekly.schedulePost': 'Schedule Post',
    'weekly.likes': 'Likes',
    'weekly.comments': 'Comments',
    'weekly.shares': 'Shares',
    'weekly.views': 'Views',
    'weekly.engagementRate': 'Engagement Rate',
    'weekly.averageEngagement': 'Average Engagement',
    'weekly.bestPerformingDay': 'Best Day',
    'weekly.bestPerformingTime': 'Best Time',
    'weekly.trendingHashtags': 'Trending Hashtags',
    'weekly.contentTypePerformance': 'Content Type Performance',
    'weekly.audienceGrowth': 'Audience Growth',
    'weekly.engagementTrend': 'Engagement Trend',
    'weekly.reachTrend': 'Reach Trend',
    'weekly.followerGrowth': 'Follower Growth',
    'weekly.postFrequency': 'Post Frequency',
    'weekly.recommendation.createMoreVideos': 'Create 2-3 video Reels for better reach',
    'weekly.recommendation.postAtOptimalTime': 'Post between 2-4 PM for maximum visibility',
    'weekly.recommendation.useTrendingHashtags': 'Use #{hashtag} for 25% more reach',
    'weekly.recommendation.increasePostFrequency': 'Increase your posting frequency to 5-7 posts per week',
    'weekly.recommendation.engageWithAudience': 'Reply to comments within 2 hours',
    'weekly.insight.videoPerformance': 'Video content performs 40% better',
    'weekly.insight.bestPostingTime': 'Best posting time: 2-4 PM',
    'weekly.insight.hashtagTrend': '#{hashtag} is trending',
    'weekly.insight.audienceActivity': 'Your audience is most active on weekdays',
    'weekly.insight.contentTypeWinner': '{type} content has the best performance',
    'weekly.noDataYet': 'No data available yet',
    'weekly.noDataDescription': 'Connect your social media accounts to get your first weekly review.',
    'weekly.connectAccounts': 'Connect Accounts',
    'weekly.generatingReport': 'Generating weekly review...',
    'weekly.reportReady': 'Your weekly review is ready!',
    'weekly.shareReport': 'Share Report',
    'weekly.downloadReport': 'Download as PDF',
    'weekly.reach': 'Reach',
    'weekly.engagement': 'Engagement',
  },
  tr: {
    // Tab Navigation
    'dashboard.title': 'Panel',
    'calendar.title': 'Takvim',
    'create.title': 'Oluştur',
    'analytics.title': 'Analitik',
    'settings.title': 'Ayarlar',
    
    // Analytics Screen
    'analytics.subtitle': 'Sosyal medya performansınızı takip edin',
    'analytics.7days': '7 Gün',
    'analytics.30days': '30 Gün',
    'analytics.90days': '90 Gün',
    'analytics.overview': 'Genel Bakış',
    'analytics.totalReach': 'Toplam Erişim',
    'analytics.engagementRate': 'Etkileşim Oranı',
    'analytics.newFollowers': 'Yeni Takipçiler',
    'analytics.profileVisits': 'Profil Ziyaretleri',
    'analytics.platformPerformance': 'Platform Performansı',
    'analytics.followers': 'Takipçiler',
    'analytics.engagement': 'Etkileşim',
    'analytics.reach': 'Erişim',
    'analytics.topPerformingPosts': 'En İyi Performans Gösteren Gönderiler',
    'analytics.aiInsights': 'AI İçgörüleri',
    'analytics.exceptional': 'Olağanüstü',
    'analytics.good': 'İyi',
    'analytics.average': 'Ortalama',
    'analytics.daysAgo': '{days} gün önce',
    'analytics.weekAgo': '1 hafta önce',
    'analytics.videoPerforming': 'Video İçerik %40 Daha İyi Performans Gösteriyor',
    'analytics.videoDescription': 'Video gönderileriniz statik görsellerden önemli ölçüde daha fazla etkileşim alıyor.',
    'analytics.createMoreVideos': 'Daha fazla video içerik oluşturun',
    'analytics.bestPostingTime': 'En İyi Paylaşım Saati: 14:00-16:00',
    'analytics.timingDescription': 'Kitleniz hafta içi öğleden sonra saatlerinde en aktif.',
    'analytics.scheduleMore': '14:00-16:00 için daha fazla gönderi planlayın',
    'analytics.hashtagTrending': '#productivity Hashtag Trend',
    'analytics.hashtagDescription': '#productivity ile yapılan gönderiler bu hafta %25 daha fazla erişim alıyor.',
    'analytics.useTrendingHashtags': 'Trend hashtag kullanın',
    
    // Language Selection
    'language.select': 'Dil Seçin',
    'language.german': 'Deutsch',
    'language.english': 'English',
    'language.turkish': 'Türkçe',
    'language.spanish': 'Español',
    'language.french': 'Français',
    
    // Common
    'common.loading': 'Yükleniyor...',
    'common.error': 'Hata',
    'common.success': 'Başarılı',
    'common.cancel': 'İptal',
    'common.save': 'Kaydet',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.done': 'Tamam',
    'common.logout': 'Çıkış Yap',
    'common.saveSettings': 'Ayarları Kaydet',
    'common.settingsSaved': 'Ayarlar Kaydedildi',
    'common.dangerZone': 'Tehlikeli Alan',
    
    // Settings Screen
    'settings.profile': 'Profil',
    'settings.account': 'Hesap',
    'settings.subscription': 'Abonelik',
    'settings.notifications': 'Bildirimler',
    'settings.security': 'Güvenlik',
    'settings.language': 'Dil ve Bölge',
    'settings.appearance': 'Görünüm',
    'settings.privacy': 'Gizlilik',
    'settings.integrations': 'Entegrasyonlar',
    'settings.team': 'Takım',
    'settings.backup': 'Yedekleme',
    'settings.feedback': 'Geri Bildirim',
    'settings.support': 'Destek',
    'settings.about': 'Hakkında',
    
    // Dashboard Screen
    'dashboard.goodMorning': 'Günaydın! 👋',
    'dashboard.readyToCreate': 'Harika içerik oluşturmaya hazır mısın?',
    'dashboard.aiContentSuggestion': 'AI İçerik Önerisi',
    'dashboard.productivityTrending': '"Verimlilik ipuçları" trend! Şimdi %40 daha fazla erişim için bir Reel oluştur.',
    'dashboard.createNow': 'Şimdi Oluştur',
    'dashboard.overview': 'Genel Bakış',
    'dashboard.totalFollowers': 'Toplam Takipçi',
    'dashboard.engagementRate': 'Etkileşim Oranı',
    'dashboard.postsThisWeek': 'Bu Hafta Gönderiler',
    'dashboard.reach': 'Erişim',
    'dashboard.platforms': 'Platformlar',
    'dashboard.recentPosts': 'Son Gönderiler',
    'dashboard.morningMotivation': 'Sabah motivasyon gönderisi',
    'dashboard.productivityTip': 'Hızlı verimlilik ipucu',
    'dashboard.industryInsights': 'Sektör içgörüleri makalesi',
    'dashboard.engagements': 'etkileşim',
    'dashboard.viewDetails': 'Detayları Görüntüle',
    'dashboard.hoursAgo': '{hours}s önce',
    'dashboard.daysAgo': '{days}g önce',
    
    // Calendar Screen
    'calendar.subtitle': 'Gönderilerinizi planlayın ve zamanlayın',
    'calendar.scheduledPosts': 'Zamanlanmış Gönderiler',
    'calendar.scheduled': 'Zamanlandı',
    'calendar.draft': 'Taslak',
    'calendar.january': 'Ocak',
    'calendar.february': 'Şubat',
    'calendar.march': 'Mart',
    'calendar.april': 'Nisan',
    'calendar.may': 'Mayıs',
    'calendar.june': 'Haziran',
    'calendar.july': 'Temmuz',
    'calendar.august': 'Ağustos',
    'calendar.september': 'Eylül',
    'calendar.october': 'Ekim',
    'calendar.november': 'Kasım',
    'calendar.december': 'Aralık',
    'calendar.monday': 'Pzt',
    'calendar.tuesday': 'Sal',
    'calendar.wednesday': 'Çar',
    'calendar.thursday': 'Per',
    'calendar.friday': 'Cum',
    'calendar.saturday': 'Cmt',
    'calendar.sunday': 'Paz',
    'calendar.morningMotivation': 'Sabah motivasyon sözü',
    'calendar.industryInsights': 'Sektör içgörüleri ve trendler',
    'calendar.quickTutorial': 'Hızlı eğitim videosu',
    'calendar.communityUpdate': 'Topluluk Güncellemesi',
    'calendar.behindScenes': 'Sahne Arkası',
    
    // Create Screen
    'create.subtitle': 'Bir sonraki viral gönderinizi oluşturun',
    'create.socialMediaAccounts': 'Sosyal Medya Hesapları',
    'create.connected': 'Bağlı',
    'create.notConnected': 'Bağlı Değil',
    'create.connect': 'Bağla',
    'create.mediaUpload': 'Medya Yükleme',
    'create.fromGallery': 'Galeriden',
    'create.files': 'Dosyalar',
    'create.uploading': 'Yükleniyor...',
    'create.aiContentGenerator': 'AI İçerik Üreticisi',
    'create.aiDescription': 'AI\'nın trendlere ve markanıza dayalı ilgi çekici içerik oluşturmasına izin verin',
    'create.generateContent': 'İçerik Oluştur',
    'create.generating': 'Oluşturuluyor...',
    'create.contentType': 'İçerik Türü',
    'create.post': 'Gönderi',
    'create.reel': 'Reel',
    'create.story': 'Hikâye',
    'create.selectPlatforms': 'Platform Seç',
    'create.description': 'Açıklama',
    'create.descriptionPlaceholder': 'Açıklamanızı buraya yazın...',
    'create.addHashtags': 'Hashtag Ekle',
    'create.aiImprove': 'AI Geliştir',
    'create.aiContentIdeas': 'AI İçerik Fikirleri',
    'create.trendingHashtags': 'Trend Hashtagler',
    'create.publishingOptions': 'Yayınlama Seçenekleri',
    'create.postNow': 'Şimdi Yayınla',
    'create.schedule': 'Zamanla',
    'create.permissionRequired': 'İzin Gerekli',
    'create.galleryPermission': 'Resim yüklemek için galerinize erişim izni gerekiyor.',
    'create.uploadError': 'Dosya yükleme hatası.',
    'create.connectAccountFirst': 'Gönderi oluşturmak için önce {platform} hesabınızı bağlayın.',
    'create.accountConnected': '{platform} başarıyla bağlandı!',
    'create.connectionFailed': 'Bağlantı başarısız. Lütfen tekrar deneyin.',
    
    // Profile Settings
    'profile.personalInfo': 'Kişisel Bilgiler',
    'profile.name': 'Ad',
    'profile.email': 'E-posta Adresi',
    'profile.phone': 'Telefon Numarası',
    'profile.billingAddress': 'Fatura Adresi',
    'profile.businessInfo': 'İş Bilgileri',
    'profile.company': 'Şirket',
    'profile.industry': 'Sektör',
    'profile.website': 'Web Sitesi',
    'profile.profilePicture': 'Profil Resmi',
    'profile.changePhoto': 'Fotoğraf Değiştir',
    'profile.visibility': 'Görünürlük',
    
    // Account Settings
    'account.changePassword': 'Şifre Değiştir',
    'account.currentPassword': 'Mevcut Şifre',
    'account.newPassword': 'Yeni Şifre',
    'account.confirmPassword': 'Şifreyi Onayla',
    'account.deleteAccount': 'Hesabı Sil',
    'account.deleteWarning': 'Bu işlem geri alınamaz',
    
    // Subscription Settings
    'subscription.currentPlan': 'Mevcut Plan',
    'subscription.monthly': 'Aylık',
    'subscription.yearly': 'Yıllık',
    'subscription.trial': 'Deneme',
    'subscription.active': 'Aktif',
    'subscription.expired': 'Süresi Dolmuş',
    'subscription.renewsOn': 'Yenileme Tarihi',
    'subscription.changePlan': 'Plan Değiştir',
    'subscription.cancelSubscription': 'Aboneliği İptal Et',
    'subscription.paymentMethod': 'Ödeme Yöntemi',
    'subscription.billingHistory': 'Fatura Geçmişi',
    
    // Notifications
    'notifications.pushNotifications': 'Push Bildirimleri',
    'notifications.emailNotifications': 'E-posta Bildirimleri',
    'notifications.postReminders': 'Gönderi Hatırlatıcıları',
    'notifications.analyticsAlerts': 'Analitik Uyarıları',
    'notifications.teamUpdates': 'Takım Güncellemeleri',
    'notifications.marketingEmails': 'Pazarlama E-postaları',
    
    // Security
    'security.twoFactor': 'İki Faktörlü Kimlik Doğrulama',
    'security.enable2FA': '2FA Etkinleştir',
    'security.disable2FA': '2FA Devre Dışı Bırak',
    'security.deviceManagement': 'Cihaz Yönetimi',
    'security.activeDevices': 'Aktif Cihazlar',
    'security.loginHistory': 'Giriş Geçmişi',
    
    // Privacy
    'privacy.dataExport': 'Veri Dışa Aktarma',
    'privacy.dataDownload': 'Verilerimi İndir',
    'privacy.privacyPolicy': 'Gizlilik Politikası',
    'privacy.termsOfService': 'Hizmet Şartları',
    'privacy.cookieSettings': 'Çerez Ayarları',
    
    // Integrations
    'integrations.socialMedia': 'Sosyal Medya Kanalları',
    'integrations.connected': 'Bağlı',
    'integrations.notConnected': 'Bağlı Değil',
    'integrations.connect': 'Bağla',
    'integrations.disconnect': 'Bağlantıyı Kes',
    'integrations.thirdParty': 'Üçüncü Taraf Araçları',
    
    // Team
    'team.members': 'Takım Üyeleri',
    'team.inviteMembers': 'Üye Davet Et',
    'team.roles': 'Roller ve İzinler',
    'team.admin': 'Yönetici',
    'team.editor': 'Editör',
    'team.viewer': 'Görüntüleyici',
    
    // Support
    'support.contactUs': 'Bize Ulaşın',
    'support.phone': 'Telefon',
    'support.email': 'E-posta',
    'support.helpCenter': 'Yardım Merkezi',
    'support.reportBug': 'Hata Bildir',
    'support.featureRequest': 'Özellik Talebi',
    'support.feedback': 'Geri Bildirim Gönder',
    
    // About
    'about.version': 'Sürüm',
    'about.buildNumber': 'Yapı Numarası',
    'about.releaseNotes': 'Sürüm Notları',
    'about.licenses': 'Lisanslar',
    'about.impressum': 'Künye',
    
    // Appearance
    'appearance.theme': 'Tema',
    'appearance.light': 'Açık',
    'appearance.dark': 'Koyu',
    'appearance.system': 'Sistem',
    'appearance.fontSize': 'Yazı Boyutu',
    'appearance.colorScheme': 'Renk Şeması',
    
    // Settings Screen - Additional translations
    'settings.manageBilling': 'yönet',
    'settings.manageDevices': 'yönet',
    'settings.manageMembers': 'yönet',
    'settings.comingSoon': 'Bu özellik yakında kullanılabilir olacak.',
    'settings.confirmLogout': 'Gerçekten çıkış yapmak istiyor musunuz?',
    'settings.confirmDelete': 'Hesap silinecek...',
    'settings.aiNotifications': 'Olağanüstü performans için AI bildirimleri',
    'settings.enabled': 'Etkin',
    'settings.disabled': 'Devre Dışı',
    'settings.contactMethod': 'Bize nasıl ulaşmak istersiniz?',
    'settings.disconnect': 'bağlantıyı kes',
    'settings.confirmDisconnect': '{platform} bağlantısını gerçekten kesmek istiyor musunuz?',
    'settings.connectPlatform': '{platform} hesabını bağla?',
    'settings.errorSaving': 'Ayarları kaydetme hatası',
    'settings.madeWith': 'SMY Agency tarafından ❤️ ile yapıldı',
    
    // Weekly Review
    'weekly.title': 'Haftalık Raporun Hazır!',
    'weekly.subtitle': 'Son 7 günün performansın burada',
    'weekly.weekOf': '{start} - {end} haftası',
    'weekly.performanceHighlights': 'Performans Öne Çıkanları',
    'weekly.totalReach': 'Toplam Erişim',
    'weekly.totalEngagement': 'Toplam Etkileşim',
    'weekly.newFollowers': 'Yeni Takipçiler',
    'weekly.profileVisits': 'Profil Ziyaretleri',
    'weekly.postsPublished': 'Yayınlanan Gönderiler',
    'weekly.comparedToLastWeek': 'geçen haftaya göre',
    'weekly.percentMore': 'geçen haftadan +%{percent} daha fazla',
    'weekly.percentLess': 'geçen haftadan %{percent} daha az',
    'weekly.sameAsLastWeek': 'Geçen hafta ile aynı',
    'weekly.topPerformingPosts': 'En İyi Performans Gösteren İçerik',
    'weekly.platformPerformance': 'Platform Performansı',
    'weekly.insights': 'İçgörüler ve Analizler',
    'weekly.recommendations': 'Gelecek Hafta İçin Öneriler',
    'weekly.viewFullAnalytics': 'Tam Analitikleri Görüntüle',
    'weekly.createContent': 'İçerik Oluştur',
    'weekly.schedulePost': 'Gönderi Planla',
    'weekly.likes': 'Beğeniler',
    'weekly.comments': 'Yorumlar',
    'weekly.shares': 'Paylaşımlar',
    'weekly.views': 'Görüntülemeler',
    'weekly.engagementRate': 'Etkileşim Oranı',
    'weekly.averageEngagement': 'Ortalama Etkileşim',
    'weekly.bestPerformingDay': 'En İyi Gün',
    'weekly.bestPerformingTime': 'En İyi Saat',
    'weekly.trendingHashtags': 'Trend Hashtagler',
    'weekly.contentTypePerformance': 'İçerik Türü Performansı',
    'weekly.audienceGrowth': 'Kitle Büyümesi',
    'weekly.engagementTrend': 'Etkileşim Trendi',
    'weekly.reachTrend': 'Erişim Trendi',
    'weekly.followerGrowth': 'Takipçi Büyümesi',
    'weekly.postFrequency': 'Gönderi Sıklığı',
    'weekly.recommendation.createMoreVideos': 'Daha iyi erişim için 2-3 video Reel oluştur',
    'weekly.recommendation.postAtOptimalTime': 'Maksimum görünürlük için 14:00-16:00 arası paylaş',
    'weekly.recommendation.useTrendingHashtags': '%25 daha fazla erişim için #{hashtag} kullan',
    'weekly.recommendation.increasePostFrequency': 'Paylaşım sıklığını haftada 5-7 gönderiye çıkar',
    'weekly.recommendation.engageWithAudience': 'Yorumlara 2 saat içinde yanıt ver',
    'weekly.insight.videoPerformance': 'Video içerik %40 daha iyi performans gösteriyor',
    'weekly.insight.bestPostingTime': 'En iyi paylaşım saati: 14:00-16:00',
    'weekly.insight.hashtagTrend': '#{hashtag} trend',
    'weekly.insight.audienceActivity': 'Kitlen hafta içi en aktif',
    'weekly.insight.contentTypeWinner': '{type} içerik en iyi performansı gösteriyor',
    'weekly.noDataYet': 'Henüz veri yok',
    'weekly.noDataDescription': 'İlk haftalık raporunu almak için sosyal medya hesaplarını bağla.',
    'weekly.connectAccounts': 'Hesapları Bağla',
    'weekly.generatingReport': 'Haftalık rapor oluşturuluyor...',
    'weekly.reportReady': 'Haftalık raporun hazır!',
    'weekly.shareReport': 'Raporu Paylaş',
    'weekly.downloadReport': 'PDF olarak İndir',
    'weekly.reach': 'Erişim',
    'weekly.engagement': 'Etkileşim',
  },
  es: {
    // Tab Navigation
    'dashboard.title': 'Panel de Control',
    'calendar.title': 'Calendario',
    'create.title': 'Crear',
    'analytics.title': 'Analíticas',
    'settings.title': 'Configuración',
    
    // Analytics Screen
    'analytics.subtitle': 'Rastrea el rendimiento de tus redes sociales',
    'analytics.7days': '7 Días',
    'analytics.30days': '30 Días',
    'analytics.90days': '90 Días',
    'analytics.overview': 'Resumen',
    'analytics.totalReach': 'Alcance Total',
    'analytics.engagementRate': 'Tasa de Interacción',
    'analytics.newFollowers': 'Nuevos Seguidores',
    'analytics.profileVisits': 'Visitas al Perfil',
    'analytics.platformPerformance': 'Rendimiento de Plataforma',
    'analytics.followers': 'Seguidores',
    'analytics.engagement': 'Interacción',
    'analytics.reach': 'Alcance',
    'analytics.topPerformingPosts': 'Publicaciones con Mejor Rendimiento',
    'analytics.aiInsights': 'Insights de IA',
    'analytics.exceptional': 'Excepcional',
    'analytics.good': 'Bueno',
    'analytics.average': 'Promedio',
    'analytics.daysAgo': 'hace {days} días',
    'analytics.weekAgo': 'hace 1 semana',
    'analytics.videoPerforming': 'El Contenido de Video Rinde 40% Mejor',
    'analytics.videoDescription': 'Tus publicaciones de video están obteniendo significativamente más interacción que las imágenes estáticas.',
    'analytics.createMoreVideos': 'Crear más contenido de video',
    'analytics.bestPostingTime': 'Mejor Hora para Publicar: 2-4 PM',
    'analytics.timingDescription': 'Tu audiencia está más activa durante las horas de la tarde en días laborables.',
    'analytics.scheduleMore': 'Programar más publicaciones para 2-4 PM',
    'analytics.hashtagTrending': 'Hashtag #productivity en Tendencia',
    'analytics.hashtagDescription': 'Las publicaciones con #productivity están obteniendo 25% más alcance esta semana.',
    'analytics.useTrendingHashtags': 'Usar hashtags en tendencia',
    
    // Language Selection
    'language.select': 'Seleccionar Idioma',
    'language.german': 'Deutsch',
    'language.english': 'English',
    'language.turkish': 'Türkçe',
    'language.spanish': 'Español',
    'language.french': 'Français',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.done': 'Hecho',
    'common.logout': 'Cerrar Sesión',
    'common.saveSettings': 'Guardar Configuración',
    'common.settingsSaved': 'Configuración Guardada',
    'common.dangerZone': 'Zona de Peligro',
    
    // Settings Screen
    'settings.profile': 'Perfil',
    'settings.account': 'Cuenta',
    'settings.subscription': 'Suscripción',
    'settings.notifications': 'Notificaciones',
    'settings.security': 'Seguridad',
    'settings.language': 'Idioma y Región',
    'settings.appearance': 'Apariencia',
    'settings.privacy': 'Privacidad',
    'settings.integrations': 'Integraciones',
    'settings.team': 'Equipo',
    'settings.backup': 'Respaldo',
    'settings.feedback': 'Comentarios',
    'settings.support': 'Soporte',
    'settings.about': 'Acerca de',
    
    // Dashboard Screen
    'dashboard.goodMorning': '¡Buenos días! 👋',
    'dashboard.readyToCreate': '¿Listo para crear contenido increíble?',
    'dashboard.aiContentSuggestion': 'Sugerencia de Contenido IA',
    'dashboard.productivityTrending': '¡"Consejos de productividad" están en tendencia! Crea un Reel ahora para 40% más alcance.',
    'dashboard.createNow': 'Crear Ahora',
    'dashboard.overview': 'Resumen',
    'dashboard.totalFollowers': 'Total de Seguidores',
    'dashboard.engagementRate': 'Tasa de Interacción',
    'dashboard.postsThisWeek': 'Publicaciones Esta Semana',
    'dashboard.reach': 'Alcance',
    'dashboard.platforms': 'Plataformas',
    'dashboard.recentPosts': 'Publicaciones Recientes',
    'dashboard.morningMotivation': 'Publicación de motivación matutina',
    'dashboard.productivityTip': 'Consejo rápido de productividad',
    'dashboard.industryInsights': 'Artículo de insights de la industria',
    'dashboard.engagements': 'interacciones',
    'dashboard.viewDetails': 'Ver Detalles',
    'dashboard.hoursAgo': 'hace {hours}h',
    'dashboard.daysAgo': 'hace {days}d',
    
    // Calendar Screen
    'calendar.subtitle': 'Planifica y programa tus publicaciones',
    'calendar.scheduledPosts': 'Publicaciones Programadas',
    'calendar.scheduled': 'Programado',
    'calendar.draft': 'Borrador',
    'calendar.january': 'Enero',
    'calendar.february': 'Febrero',
    'calendar.march': 'Marzo',
    'calendar.april': 'Abril',
    'calendar.may': 'Mayo',
    'calendar.june': 'Junio',
    'calendar.july': 'Julio',
    'calendar.august': 'Agosto',
    'calendar.september': 'Septiembre',
    'calendar.october': 'Octubre',
    'calendar.november': 'Noviembre',
    'calendar.december': 'Diciembre',
    'calendar.monday': 'Lun',
    'calendar.tuesday': 'Mar',
    'calendar.wednesday': 'Mié',
    'calendar.thursday': 'Jue',
    'calendar.friday': 'Vie',
    'calendar.saturday': 'Sáb',
    'calendar.sunday': 'Dom',
    'calendar.morningMotivation': 'Cita de motivación matutina',
    'calendar.industryInsights': 'Insights y tendencias de la industria',
    'calendar.quickTutorial': 'Video tutorial rápido',
    'calendar.communityUpdate': 'Actualización de la Comunidad',
    'calendar.behindScenes': 'Detrás de Escena',
    
    // Create Screen
    'create.subtitle': 'Crea tu próxima publicación viral',
    'create.socialMediaAccounts': 'Cuentas de Redes Sociales',
    'create.connected': 'Conectado',
    'create.notConnected': 'No Conectado',
    'create.connect': 'Conectar',
    'create.mediaUpload': 'Subir Medios',
    'create.fromGallery': 'Desde Galería',
    'create.files': 'Archivos',
    'create.uploading': 'Subiendo...',
    'create.aiContentGenerator': 'Generador de Contenido IA',
    'create.aiDescription': 'Deja que la IA cree contenido atractivo basado en tendencias y tu marca',
    'create.generateContent': 'Generar Contenido',
    'create.generating': 'Generando...',
    'create.contentType': 'Tipo de Contenido',
    'create.post': 'Publicación',
    'create.reel': 'Reel',
    'create.story': 'Historia',
    'create.selectPlatforms': 'Seleccionar Plataformas',
    'create.description': 'Descripción',
    'create.descriptionPlaceholder': 'Escribe tu descripción aquí...',
    'create.addHashtags': 'Agregar Hashtags',
    'create.aiImprove': 'Mejorar con IA',
    'create.aiContentIdeas': 'Ideas de Contenido IA',
    'create.trendingHashtags': 'Hashtags en Tendencia',
    'create.publishingOptions': 'Opciones de Publicación',
    'create.postNow': 'Publicar Ahora',
    'create.schedule': 'Programar',
    'create.permissionRequired': 'Permiso Requerido',
    'create.galleryPermission': 'Necesitamos acceso a tu galería para subir imágenes.',
    'create.uploadError': 'Error al subir archivos.',
    'create.connectAccountFirst': 'Por favor conecta tu cuenta de {platform} primero para crear publicaciones.',
    'create.accountConnected': '¡{platform} conectado exitosamente!',
    'create.connectionFailed': 'Conexión fallida. Por favor intenta de nuevo.',
    
    // Profile Settings
    'profile.personalInfo': 'Información Personal',
    'profile.name': 'Nombre',
    'profile.email': 'Dirección de Correo',
    'profile.phone': 'Número de Teléfono',
    'profile.billingAddress': 'Dirección de Facturación',
    'profile.businessInfo': 'Información Empresarial',
    'profile.company': 'Empresa',
    'profile.industry': 'Industria',
    'profile.website': 'Sitio Web',
    'profile.profilePicture': 'Foto de Perfil',
    'profile.changePhoto': 'Cambiar Foto',
    'profile.visibility': 'Visibilidad',
    
    // Account Settings
    'account.changePassword': 'Cambiar Contraseña',
    'account.currentPassword': 'Contraseña Actual',
    'account.newPassword': 'Nueva Contraseña',
    'account.confirmPassword': 'Confirmar Contraseña',
    'account.deleteAccount': 'Eliminar Cuenta',
    'account.deleteWarning': 'Esta acción no se puede deshacer',
    
    // Subscription Settings
    'subscription.currentPlan': 'Plan Actual',
    'subscription.monthly': 'Mensual',
    'subscription.yearly': 'Anual',
    'subscription.trial': 'Prueba',
    'subscription.active': 'Activo',
    'subscription.expired': 'Expirado',
    'subscription.renewsOn': 'Se renueva el',
    'subscription.changePlan': 'Cambiar Plan',
    'subscription.cancelSubscription': 'Cancelar Suscripción',
    'subscription.paymentMethod': 'Método de Pago',
    'subscription.billingHistory': 'Historial de Facturación',
    
    // Notifications
    'notifications.pushNotifications': 'Notificaciones Push',
    'notifications.emailNotifications': 'Notificaciones por Correo',
    'notifications.postReminders': 'Recordatorios de Publicaciones',
    'notifications.analyticsAlerts': 'Alertas de Analíticas',
    'notifications.teamUpdates': 'Actualizaciones del Equipo',
    'notifications.marketingEmails': 'Correos de Marketing',
    
    // Security
    'security.twoFactor': 'Autenticación de Dos Factores',
    'security.enable2FA': 'Habilitar 2FA',
    'security.disable2FA': 'Deshabilitar 2FA',
    'security.deviceManagement': 'Gestión de Dispositivos',
    'security.activeDevices': 'Dispositivos Activos',
    'security.loginHistory': 'Historial de Inicios de Sesión',
    
    // Privacy
    'privacy.dataExport': 'Exportación de Datos',
    'privacy.dataDownload': 'Descargar Mis Datos',
    'privacy.privacyPolicy': 'Política de Privacidad',
    'privacy.termsOfService': 'Términos de Servicio',
    'privacy.cookieSettings': 'Configuración de Cookies',
    
    // Integrations
    'integrations.socialMedia': 'Canales de Redes Sociales',
    'integrations.connected': 'Conectado',
    'integrations.notConnected': 'No Conectado',
    'integrations.connect': 'Conectar',
    'integrations.disconnect': 'Desconectar',
    'integrations.thirdParty': 'Herramientas de Terceros',
    
    // Team
    'team.members': 'Miembros del Equipo',
    'team.inviteMembers': 'Invitar Miembros',
    'team.roles': 'Roles y Permisos',
    'team.admin': 'Administrador',
    'team.editor': 'Editor',
    'team.viewer': 'Visualizador',
    
    // Support
    'support.contactUs': 'Contáctanos',
    'support.phone': 'Teléfono',
    'support.email': 'Correo',
    'support.helpCenter': 'Centro de Ayuda',
    'support.reportBug': 'Reportar Error',
    'support.featureRequest': 'Solicitud de Función',
    'support.feedback': 'Enviar Comentarios',
    
    // About
    'about.version': 'Versión',
    'about.buildNumber': 'Número de Compilación',
    'about.releaseNotes': 'Notas de Lanzamiento',
    'about.licenses': 'Licencias',
    'about.impressum': 'Aviso Legal',
    
    // Appearance
    'appearance.theme': 'Tema',
    'appearance.light': 'Claro',
    'appearance.dark': 'Oscuro',
    'appearance.system': 'Sistema',
    'appearance.fontSize': 'Tamaño de Fuente',
    'appearance.colorScheme': 'Esquema de Color',
    
    // Settings Screen - Additional translations
    'settings.manageBilling': 'gestionar',
    'settings.manageDevices': 'gestionar',
    'settings.manageMembers': 'gestionar',
    'settings.comingSoon': 'Esta función estará disponible pronto.',
    'settings.confirmLogout': '¿Realmente quieres cerrar sesión?',
    'settings.confirmDelete': 'La cuenta será eliminada...',
    'settings.aiNotifications': 'Notificaciones de IA para rendimiento excepcional',
    'settings.enabled': 'Habilitado',
    'settings.disabled': 'Deshabilitado',
    'settings.contactMethod': '¿Cómo te gustaría contactarnos?',
    'settings.disconnect': 'desconectar',
    'settings.confirmDisconnect': '¿Realmente quieres desconectar {platform}?',
    'settings.connectPlatform': '¿Conectar cuenta de {platform}?',
    'settings.errorSaving': 'Error al guardar configuración',
    'settings.madeWith': 'Hecho con ❤️ por SMY Agency',
    
    // Weekly Review
    'weekly.title': '¡Tu Resumen Semanal Está Listo!',
    'weekly.subtitle': 'Aquí está tu rendimiento de los últimos 7 días',
    'weekly.weekOf': 'Semana del {start} - {end}',
    'weekly.performanceHighlights': 'Aspectos Destacados del Rendimiento',
    'weekly.totalReach': 'Alcance Total',
    'weekly.totalEngagement': 'Interacción Total',
    'weekly.newFollowers': 'Nuevos Seguidores',
    'weekly.profileVisits': 'Visitas al Perfil',
    'weekly.postsPublished': 'Publicaciones Realizadas',
    'weekly.comparedToLastWeek': 'comparado con la semana pasada',
    'weekly.percentMore': '+{percent}% más que la semana pasada',
    'weekly.percentLess': '{percent}% menos que la semana pasada',
    'weekly.sameAsLastWeek': 'Igual que la semana pasada',
    'weekly.topPerformingPosts': 'Contenido con Mejor Rendimiento',
    'weekly.platformPerformance': 'Rendimiento por Plataforma',
    'weekly.insights': 'Insights y Análisis',
    'weekly.recommendations': 'Recomendaciones para la Próxima Semana',
    'weekly.viewFullAnalytics': 'Ver Análisis Completo',
    'weekly.createContent': 'Crear Contenido',
    'weekly.schedulePost': 'Programar Publicación',
    'weekly.likes': 'Me Gusta',
    'weekly.comments': 'Comentarios',
    'weekly.shares': 'Compartidos',
    'weekly.views': 'Visualizaciones',
    'weekly.engagementRate': 'Tasa de Interacción',
    'weekly.averageEngagement': 'Interacción Promedio',
    'weekly.bestPerformingDay': 'Mejor Día',
    'weekly.bestPerformingTime': 'Mejor Hora',
    'weekly.trendingHashtags': 'Hashtags en Tendencia',
    'weekly.contentTypePerformance': 'Rendimiento por Tipo de Contenido',
    'weekly.audienceGrowth': 'Crecimiento de Audiencia',
    'weekly.engagementTrend': 'Tendencia de Interacción',
    'weekly.reachTrend': 'Tendencia de Alcance',
    'weekly.followerGrowth': 'Crecimiento de Seguidores',
    'weekly.postFrequency': 'Frecuencia de Publicaciones',
    'weekly.recommendation.createMoreVideos': 'Crea 2-3 Reels de video para mejor alcance',
    'weekly.recommendation.postAtOptimalTime': 'Publica entre 2-4 PM para máxima visibilidad',
    'weekly.recommendation.useTrendingHashtags': 'Usa #{hashtag} para 25% más alcance',
    'weekly.recommendation.increasePostFrequency': 'Aumenta tu frecuencia de publicación a 5-7 posts por semana',
    'weekly.recommendation.engageWithAudience': 'Responde comentarios dentro de 2 horas',
    'weekly.insight.videoPerformance': 'El contenido de video rinde 40% mejor',
    'weekly.insight.bestPostingTime': 'Mejor hora para publicar: 2-4 PM',
    'weekly.insight.hashtagTrend': '#{hashtag} está en tendencia',
    'weekly.insight.audienceActivity': 'Tu audiencia está más activa entre semana',
    'weekly.insight.contentTypeWinner': 'El contenido {type} tiene el mejor rendimiento',
    'weekly.noDataYet': 'Aún no hay datos disponibles',
    'weekly.noDataDescription': 'Conecta tus cuentas de redes sociales para obtener tu primer resumen semanal.',
    'weekly.connectAccounts': 'Conectar Cuentas',
    'weekly.generatingReport': 'Generando resumen semanal...',
    'weekly.reportReady': '¡Tu resumen semanal está listo!',
    'weekly.shareReport': 'Compartir Reporte',
    'weekly.downloadReport': 'Descargar como PDF',
    'weekly.reach': 'Alcance',
    'weekly.engagement': 'Interacción',
  },
  fr: {
    // Tab Navigation
    'dashboard.title': 'Tableau de Bord',
    'calendar.title': 'Calendrier',
    'create.title': 'Créer',
    'analytics.title': 'Analytiques',
    'settings.title': 'Paramètres',
    
    // Analytics Screen
    'analytics.subtitle': 'Suivez les performances de vos réseaux sociaux',
    'analytics.7days': '7 Jours',
    'analytics.30days': '30 Jours',
    'analytics.90days': '90 Jours',
    'analytics.overview': 'Aperçu',
    'analytics.totalReach': 'Portée Totale',
    'analytics.engagementRate': 'Taux d\'Engagement',
    'analytics.newFollowers': 'Nouveaux Abonnés',
    'analytics.profileVisits': 'Visites de Profil',
    'analytics.platformPerformance': 'Performance de Plateforme',
    'analytics.followers': 'Abonnés',
    'analytics.engagement': 'Engagement',
    'analytics.reach': 'Portée',
    'analytics.topPerformingPosts': 'Publications les Plus Performantes',
    'analytics.aiInsights': 'Insights IA',
    'analytics.exceptional': 'Exceptionnel',
    'analytics.good': 'Bon',
    'analytics.average': 'Moyen',
    'analytics.daysAgo': 'il y a {days} jours',
    'analytics.weekAgo': 'il y a 1 semaine',
    'analytics.videoPerforming': 'Le Contenu Vidéo Performe 40% Mieux',
    'analytics.videoDescription': 'Vos publications vidéo obtiennent significativement plus d\'engagement que les images statiques.',
    'analytics.createMoreVideos': 'Créer plus de contenu vidéo',
    'analytics.bestPostingTime': 'Meilleur Moment pour Publier: 14h-16h',
    'analytics.timingDescription': 'Votre audience est plus active pendant les heures d\'après-midi en semaine.',
    'analytics.scheduleMore': 'Programmer plus de publications pour 14h-16h',
    'analytics.hashtagTrending': 'Hashtag #productivity en Tendance',
    'analytics.hashtagDescription': 'Les publications avec #productivity obtiennent 25% plus de portée cette semaine.',
    'analytics.useTrendingHashtags': 'Utiliser les hashtags tendance',
    
    // Language Selection
    'language.select': 'Sélectionner la Langue',
    'language.german': 'Deutsch',
    'language.english': 'English',
    'language.turkish': 'Türkçe',
    'language.spanish': 'Español',
    'language.french': 'Français',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Sauvegarder',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.done': 'Terminé',
    'common.logout': 'Se Déconnecter',
    'common.saveSettings': 'Sauvegarder les Paramètres',
    'common.settingsSaved': 'Paramètres Sauvegardés',
    'common.dangerZone': 'Zone Dangereuse',
    
    // Settings Screen
    'settings.profile': 'Profil',
    'settings.account': 'Compte',
    'settings.subscription': 'Abonnement',
    'settings.notifications': 'Notifications',
    'settings.security': 'Sécurité',
    'settings.language': 'Langue et Région',
    'settings.appearance': 'Apparence',
    'settings.privacy': 'Confidentialité',
    'settings.integrations': 'Intégrations',
    'settings.team': 'Équipe',
    'settings.backup': 'Sauvegarde',
    'settings.feedback': 'Commentaires',
    'settings.support': 'Support',
    'settings.about': 'À propos',
    
    // Dashboard Screen
    'dashboard.goodMorning': 'Bonjour ! 👋',
    'dashboard.readyToCreate': 'Prêt à créer du contenu incroyable ?',
    'dashboard.aiContentSuggestion': 'Suggestion de Contenu IA',
    'dashboard.productivityTrending': '"Conseils de productivité" sont tendance ! Créez un Reel maintenant pour 40% plus de portée.',
    'dashboard.createNow': 'Créer Maintenant',
    'dashboard.overview': 'Aperçu',
    'dashboard.totalFollowers': 'Total des Abonnés',
    'dashboard.engagementRate': 'Taux d\'Engagement',
    'dashboard.postsThisWeek': 'Publications Cette Semaine',
    'dashboard.reach': 'Portée',
    'dashboard.platforms': 'Plateformes',
    'dashboard.recentPosts': 'Publications Récentes',
    'dashboard.morningMotivation': 'Publication de motivation matinale',
    'dashboard.productivityTip': 'Conseil rapide de productivité',
    'dashboard.industryInsights': 'Article d\'insights de l\'industrie',
    'dashboard.engagements': 'engagements',
    'dashboard.viewDetails': 'Voir les Détails',
    'dashboard.hoursAgo': 'il y a {hours}h',
    'dashboard.daysAgo': 'il y a {days}j',
    
    // Calendar Screen
    'calendar.subtitle': 'Planifiez et programmez vos publications',
    'calendar.scheduledPosts': 'Publications Programmées',
    'calendar.scheduled': 'Programmé',
    'calendar.draft': 'Brouillon',
    'calendar.january': 'Janvier',
    'calendar.february': 'Février',
    'calendar.march': 'Mars',
    'calendar.april': 'Avril',
    'calendar.may': 'Mai',
    'calendar.june': 'Juin',
    'calendar.july': 'Juillet',
    'calendar.august': 'Août',
    'calendar.september': 'Septembre',
    'calendar.october': 'Octobre',
    'calendar.november': 'Novembre',
    'calendar.december': 'Décembre',
    'calendar.monday': 'Lun',
    'calendar.tuesday': 'Mar',
    'calendar.wednesday': 'Mer',
    'calendar.thursday': 'Jeu',
    'calendar.friday': 'Ven',
    'calendar.saturday': 'Sam',
    'calendar.sunday': 'Dim',
    'calendar.morningMotivation': 'Citation de motivation matinale',
    'calendar.industryInsights': 'Insights et tendances de l\'industrie',
    'calendar.quickTutorial': 'Vidéo tutoriel rapide',
    'calendar.communityUpdate': 'Mise à Jour de la Communauté',
    'calendar.behindScenes': 'Coulisses',
    
    // Create Screen
    'create.subtitle': 'Créez votre prochaine publication virale',
    'create.socialMediaAccounts': 'Comptes de Réseaux Sociaux',
    'create.connected': 'Connecté',
    'create.notConnected': 'Non Connecté',
    'create.connect': 'Connecter',
    'create.mediaUpload': 'Téléchargement de Médias',
    'create.fromGallery': 'Depuis la Galerie',
    'create.files': 'Fichiers',
    'create.uploading': 'Téléchargement...',
    'create.aiContentGenerator': 'Générateur de Contenu IA',
    'create.aiDescription': 'Laissez l\'IA créer du contenu engageant basé sur les tendances et votre marque',
    'create.generateContent': 'Générer du Contenu',
    'create.generating': 'Génération...',
    'create.contentType': 'Type de Contenu',
    'create.post': 'Publication',
    'create.reel': 'Reel',
    'create.story': 'Story',
    'create.selectPlatforms': 'Sélectionner les Plateformes',
    'create.description': 'Description',
    'create.descriptionPlaceholder': 'Écrivez votre description ici...',
    'create.addHashtags': 'Ajouter des Hashtags',
    'create.aiImprove': 'Améliorer avec IA',
    'create.aiContentIdeas': 'Idées de Contenu IA',
    'create.trendingHashtags': 'Hashtags Tendance',
    'create.publishingOptions': 'Options de Publication',
    'create.postNow': 'Publier Maintenant',
    'create.schedule': 'Programmer',
    'create.permissionRequired': 'Permission Requise',
    'create.galleryPermission': 'Nous avons besoin d\'accéder à votre galerie pour télécharger des images.',
    'create.uploadError': 'Erreur lors du téléchargement des fichiers.',
    'create.connectAccountFirst': 'Veuillez d\'abord connecter votre compte {platform} pour créer des publications.',
    'create.accountConnected': '{platform} connecté avec succès !',
    'create.connectionFailed': 'Connexion échouée. Veuillez réessayer.',
    
    // Profile Settings
    'profile.personalInfo': 'Informations Personnelles',
    'profile.name': 'Nom',
    'profile.email': 'Adresse E-mail',
    'profile.phone': 'Numéro de Téléphone',
    'profile.billingAddress': 'Adresse de Facturation',
    'profile.businessInfo': 'Informations Professionnelles',
    'profile.company': 'Entreprise',
    'profile.industry': 'Secteur',
    'profile.website': 'Site Web',
    'profile.profilePicture': 'Photo de Profil',
    'profile.changePhoto': 'Changer la Photo',
    'profile.visibility': 'Visibilité',
    
    // Account Settings
    'account.changePassword': 'Changer le Mot de Passe',
    'account.currentPassword': 'Mot de Passe Actuel',
    'account.newPassword': 'Nouveau Mot de Passe',
    'account.confirmPassword': 'Confirmer le Mot de Passe',
    'account.deleteAccount': 'Supprimer le Compte',
    'account.deleteWarning': 'Cette action ne peut pas être annulée',
    
    // Subscription Settings
    'subscription.currentPlan': 'Plan Actuel',
    'subscription.monthly': 'Mensuel',
    'subscription.yearly': 'Annuel',
    'subscription.trial': 'Essai',
    'subscription.active': 'Actif',
    'subscription.expired': 'Expiré',
    'subscription.renewsOn': 'Se renouvelle le',
    'subscription.changePlan': 'Changer de Plan',
    'subscription.cancelSubscription': 'Annuler l\'Abonnement',
    'subscription.paymentMethod': 'Méthode de Paiement',
    'subscription.billingHistory': 'Historique de Facturation',
    
    // Notifications
    'notifications.pushNotifications': 'Notifications Push',
    'notifications.emailNotifications': 'Notifications par E-mail',
    'notifications.postReminders': 'Rappels de Publications',
    'notifications.analyticsAlerts': 'Alertes d\'Analytiques',
    'notifications.teamUpdates': 'Mises à Jour d\'Équipe',
    'notifications.marketingEmails': 'E-mails Marketing',
    
    // Security
    'security.twoFactor': 'Authentification à Deux Facteurs',
    'security.enable2FA': 'Activer 2FA',
    'security.disable2FA': 'Désactiver 2FA',
    'security.deviceManagement': 'Gestion des Appareils',
    'security.activeDevices': 'Appareils Actifs',
    'security.loginHistory': 'Historique de Connexion',
    
    // Privacy
    'privacy.dataExport': 'Exportation de Données',
    'privacy.dataDownload': 'Télécharger Mes Données',
    'privacy.privacyPolicy': 'Politique de Confidentialité',
    'privacy.termsOfService': 'Conditions de Service',
    'privacy.cookieSettings': 'Paramètres des Cookies',
    
    // Integrations
    'integrations.socialMedia': 'Canaux de Réseaux Sociaux',
    'integrations.connected': 'Connecté',
    'integrations.notConnected': 'Non Connecté',
    'integrations.connect': 'Connecter',
    'integrations.disconnect': 'Déconnecter',
    'integrations.thirdParty': 'Outils Tiers',
    
    // Team
    'team.members': 'Membres de l\'Équipe',
    'team.inviteMembers': 'Inviter des Membres',
    'team.roles': 'Rôles et Permissions',
    'team.admin': 'Administrateur',
    'team.editor': 'Éditeur',
    'team.viewer': 'Visualiseur',
    
    // Support
    'support.contactUs': 'Nous Contacter',
    'support.phone': 'Téléphone',
    'support.email': 'E-mail',
    'support.helpCenter': 'Centre d\'Aide',
    'support.reportBug': 'Signaler un Bug',
    'support.featureRequest': 'Demande de Fonctionnalité',
    'support.feedback': 'Envoyer des Commentaires',
    
    // About
    'about.version': 'Version',
    'about.buildNumber': 'Numéro de Build',
    'about.releaseNotes': 'Notes de Version',
    'about.licenses': 'Licences',
    'about.impressum': 'Mentions Légales',
    
    // Appearance
    'appearance.theme': 'Thème',
    'appearance.light': 'Clair',
    'appearance.dark': 'Sombre',
    'appearance.system': 'Système',
    'appearance.fontSize': 'Taille de Police',
    'appearance.colorScheme': 'Schéma de Couleurs',
    
    // Settings Screen - Additional translations
    'settings.manageBilling': 'gérer',
    'settings.manageDevices': 'gérer',
    'settings.manageMembers': 'gérer',
    'settings.comingSoon': 'Cette fonctionnalité sera bientôt disponible.',
    'settings.confirmLogout': 'Voulez-vous vraiment vous déconnecter ?',
    'settings.confirmDelete': 'Le compte sera supprimé...',
    'settings.aiNotifications': 'Notifications IA pour performance exceptionnelle',
    'settings.enabled': 'Activé',
    'settings.disabled': 'Désactivé',
    'settings.contactMethod': 'Comment souhaitez-vous nous contacter ?',
    'settings.disconnect': 'déconnecter',
    'settings.confirmDisconnect': 'Voulez-vous vraiment déconnecter {platform} ?',
    'settings.connectPlatform': 'Connecter le compte {platform} ?',
    'settings.errorSaving': 'Erreur lors de la sauvegarde des paramètres',
    'settings.madeWith': 'Fait avec ❤️ par SMY Agency',
    
    // Weekly Review
    'weekly.title': 'Votre Résumé Hebdomadaire est Prêt !',
    'weekly.subtitle': 'Voici votre performance des 7 derniers jours',
    'weekly.weekOf': 'Semaine du {start} - {end}',
    'weekly.performanceHighlights': 'Points Forts de la Performance',
    'weekly.totalReach': 'Portée Totale',
    'weekly.totalEngagement': 'Engagement Total',
    'weekly.newFollowers': 'Nouveaux Abonnés',
    'weekly.profileVisits': 'Visites de Profil',
    'weekly.postsPublished': 'Publications Publiées',
    'weekly.comparedToLastWeek': 'par rapport à la semaine dernière',
    'weekly.percentMore': '+{percent}% de plus que la semaine dernière',
    'weekly.percentLess': '{percent}% de moins que la semaine dernière',
    'weekly.sameAsLastWeek': 'Identique à la semaine dernière',
    'weekly.topPerformingPosts': 'Contenu le Plus Performant',
    'weekly.platformPerformance': 'Performance par Plateforme',
    'weekly.insights': 'Insights et Analyses',
    'weekly.recommendations': 'Recommandations pour la Semaine Prochaine',
    'weekly.viewFullAnalytics': 'Voir les Analyses Complètes',
    'weekly.createContent': 'Créer du Contenu',
    'weekly.schedulePost': 'Programmer une Publication',
    'weekly.likes': 'J\'aime',
    'weekly.comments': 'Commentaires',
    'weekly.shares': 'Partages',
    'weekly.views': 'Vues',
    'weekly.engagementRate': 'Taux d\'Engagement',
    'weekly.averageEngagement': 'Engagement Moyen',
    'weekly.bestPerformingDay': 'Meilleur Jour',
    'weekly.bestPerformingTime': 'Meilleure Heure',
    'weekly.trendingHashtags': 'Hashtags Tendance',
    'weekly.contentTypePerformance': 'Performance par Type de Contenu',
    'weekly.audienceGrowth': 'Croissance de l\'Audience',
    'weekly.engagementTrend': 'Tendance d\'Engagement',
    'weekly.reachTrend': 'Tendance de Portée',
    'weekly.followerGrowth': 'Croissance des Abonnés',
    'weekly.postFrequency': 'Fréquence de Publication',
    'weekly.recommendation.createMoreVideos': 'Créez 2-3 Reels vidéo pour une meilleure portée',
    'weekly.recommendation.postAtOptimalTime': 'Publiez entre 14h-16h pour une visibilité maximale',
    'weekly.recommendation.useTrendingHashtags': 'Utilisez #{hashtag} pour 25% de portée en plus',
    'weekly.recommendation.increasePostFrequency': 'Augmentez votre fréquence de publication à 5-7 posts par semaine',
    'weekly.recommendation.engageWithAudience': 'Répondez aux commentaires dans les 2 heures',
    'weekly.insight.videoPerformance': 'Le contenu vidéo performe 40% mieux',
    'weekly.insight.bestPostingTime': 'Meilleur moment pour publier : 14h-16h',
    'weekly.insight.hashtagTrend': '#{hashtag} est en tendance',
    'weekly.insight.audienceActivity': 'Votre audience est plus active en semaine',
    'weekly.insight.contentTypeWinner': 'Le contenu {type} a la meilleure performance',
    'weekly.noDataYet': 'Aucune donnée disponible pour le moment',
    'weekly.noDataDescription': 'Connectez vos comptes de réseaux sociaux pour obtenir votre premier résumé hebdomadaire.',
    'weekly.connectAccounts': 'Connecter les Comptes',
    'weekly.generatingReport': 'Génération du résumé hebdomadaire...',
    'weekly.reportReady': 'Votre résumé hebdomadaire est prêt !',
    'weekly.shareReport': 'Partager le Rapport',
    'weekly.downloadReport': 'Télécharger en PDF',
    'weekly.reach': 'Portée',
    'weekly.engagement': 'Engagement',
  },
};

export const [LanguageProvider, useLanguage] = createContextHook((): LanguageContextType => {
  const [language, setLanguageState] = useState<Language>('de');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem('selectedLanguage');
      if (savedLanguage && typeof savedLanguage === 'string' && savedLanguage.trim()) {
        // Validate that it's a simple string, not JSON
        if (savedLanguage.startsWith('{') || savedLanguage.startsWith('[')) {
          console.warn('Invalid language data format, clearing storage');
          await AsyncStorage.removeItem('selectedLanguage');
          setLanguageState('de');
          return;
        }
        
        if (Object.keys(translations).includes(savedLanguage)) {
          setLanguageState(savedLanguage as Language);
        } else {
          // Default to German if invalid language
          setLanguageState('de');
          await AsyncStorage.removeItem('selectedLanguage');
        }
      } else {
        // Default to German if no language is saved
        setLanguageState('de');
      }
    } catch (error) {
      console.error('Error loading language:', error);
      // Clear corrupted data and fallback to German
      try {
        await AsyncStorage.removeItem('selectedLanguage');
      } catch (clearError) {
        console.error('Error clearing corrupted language data:', clearError);
      }
      setLanguageState('de');
    } finally {
      setIsLoading(false);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem('selectedLanguage', lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string): string => {
    try {
      const translation = translations[language]?.[key];
      return translation || key;
    } catch (error) {
      console.warn('Translation error for key:', key, error);
      return key;
    }
  };

  return {
    language,
    setLanguage,
    t,
    isLoading,
  };
});