ENV['RCT_NEW_ARCH_ENABLED'] = '0'
ENV['RCT_FABRIC_ENABLED'] = '0'

platform :ios, '15.1'

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods.rb")

require 'json'
podfile_properties = JSON.parse(
  File.read(File.join(__dir__, 'Podfile.properties.json'))
) rescue {}

target 'iostemplatefix' do
  use_expo_modules!

  config = use_native_modules!

  use_react_native!(
  :path             => config[:reactNativePath],
  :hermes_enabled   => false,
  :fabric_enabled   => false,
  :new_arch_enabled => false
)
end

post_install do |installer|
  # React Native / Expo post install
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => false
  )

  # ✅ FIX: Xcode Sandbox rsync deny (Hermes)
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end

  # iOS Deployment Target fix
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
    end
  end
end
