platform :ios, '15.1'

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods.rb")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

# Patch: SDWebImageAVIFCoder -> libavif-Xcode (ohne .name-Crash)
pre_install do |installer|
  installer.pod_targets.each do |pod|
    next unless pod.name == 'SDWebImageAVIFCoder'

    puts "🔧 Patching SDWebImageAVIFCoder to use libavif-Xcode"

    if pod.dependencies.is_a?(Array)
      pod.dependencies.map! do |dependency|
        dep_name = dependency.respond_to?(:name) ? dependency.name : dependency
        if dep_name == 'libavif'
          if dependency.respond_to?(:name)
            dependency.instance_variable_set(:@name, 'libavif-Xcode')
            dependency
          else
            'libavif-Xcode'
          end
        else
          dependency
        end
      end
    end
  end
end

target 'iostemplatefix' do
  use_expo_modules!

  config = use_native_modules!

  use_react_native!(
    :fabric_enabled => true,
    :new_arch_enabled => true,
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )
end

post_install do |installer|
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => false
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
    end
  end
end
